name: build
on: [ workflow_dispatch ]
#on:
#  pull_request:
#    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest
#    if: github.event.pull_request.merged == true
    steps:
      - name: Run package creation
        run: |
          python -m pip install --user --upgrade build
          python -m build
      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: awesome-calculator
          path: src/dist
