name: ruff
on: [ push, pull_request, workflow_dispatch ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ruff-check
        uses: chartboost/ruff-action@v1
        with:
          args: "check --output-format=github"

      - name: Ruff-format
        if: always()
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
